services:
  postgres:
    image: postgis/postgis:17-3.5 
    container_name: cold-postgis
    restart: "no"
    environment:
      POSTGRES_USER: ozzu 
      POSTGRES_PASSWORD: marij 
      POSTGRES_DB: gis 
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - server_my_custom_network

networks:
  server_my_custom_network:
    external: true

volumes:
  postgres_data:

